// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1i-_25cP_xFnNKgaan7RdtDPvMvAVms4',
    appId: '1:504874264503:web:8ae29abca50b54190b2a32',
    messagingSenderId: '504874264503',
    projectId: 'projects-personal-f4232',
    authDomain: 'projects-personal-f4232.firebaseapp.com',
    storageBucket: 'projects-personal-f4232.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptJcv32gc4UJp1FluDFQFlM7yzDP8Yic',
    appId: '1:504874264503:android:430a6ea4c89f9f000b2a32',
    messagingSenderId: '504874264503',
    projectId: 'projects-personal-f4232',
    storageBucket: 'projects-personal-f4232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCmJbQ1Kiqctg9yk7Pg2m1cwgpNtJR50',
    appId: '1:504874264503:ios:b26094d8cb7a91600b2a32',
    messagingSenderId: '504874264503',
    projectId: 'projects-personal-f4232',
    storageBucket: 'projects-personal-f4232.appspot.com',
    iosClientId: '504874264503-j08lt1f0hk4oeupm1bh2vfvq8nlekrb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeTicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCmJbQ1Kiqctg9yk7Pg2m1cwgpNtJR50',
    appId: '1:504874264503:ios:3b8d3b6d666c33910b2a32',
    messagingSenderId: '504874264503',
    projectId: 'projects-personal-f4232',
    storageBucket: 'projects-personal-f4232.appspot.com',
    iosClientId: '504874264503-gfsl1440r24kasm56r3aego9oddip9c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeTicker.RunnerTests',
  );
}
